### ISSUE TITLE
Latest version (sha-fdf2277) results in could not build server_names_hash error

### ISSUE THREAD

**Issue by Jack-Overflow** [tofran/nginx-with-substitutions-filter-docker#4]
**Problem:** 
After updating to the latest version of this image (`sha-fdf2277`) my configuration has gone from working to producing this error.
![Image](https://github.com/user-attachments/assets/5c0b626c-4410-457d-8799-c779171106e9)

Does the image support providing the `server_names_hash_bucket_size` directive without overwriting the entire base nginx.conf? I've had to go back to `sha-f8acc92` which is working.

Current configuration:
```
version: "3.8"
services:
  nginx:
    container_name: fe-dev-env-reverse-proxy
    image: tofran/nginx-with-substitutions-filter:latest
    environment:
      - OS_RUNNING_DOCKER_USER_NAME=${USER}
    volumes:
      - ./dev-reverse-proxy/sites:/etc/nginx/templates
      - ./dev-reverse-proxy/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    networks:
      fe_dev_env_http_proxy:
        aliases:
          - services.localdev
    restart: unless-stopped

networks:
  fe_dev_env_http_proxy:
    name: fe_dev_env_http_proxy
```
